### ISSUE TITLE
Publish fix for #43?

### ISSUE THREAD

**Issue by yrns** [stoeffel/futurize#57]
Looking for a version on npm that has the fix for #43. Thanks!

**Comment by Avaq** [comment]
Ping! If the fix is not published, I will have to remove the library from the Fluture readme. The two libraries are unfortunately not compatible currently. :(

**Comment by stoeffel** [comment]
published v1.1.0. Sorry about that. @Avaq I added you to the package on npm and to this org. I hope that's okay. don't feel obligated to do anything. but feel free to publish stuff if it's blocking.
