### ISSUE TITLE
call a module named "test" in current working path instead of the builtin one

### ISSUE THREAD

**Issue by abc19899** [stoeffel/futurize#78]
in python2, after futurize,

it add codes:
standard_library.install_aliases()
which have these code inside:
import test

the code is mean to cll python2's standard test module. But if i have a test.py beside my starter.py,  when i run starter.py , it will call test.py.

Is it a bug or should i rename all test.py?

**Comment by abc19899** [comment]
oh, i think i have go to a wrong place. forgive me.

**Comment by Avaq** [comment]
> i think i have go to a wrong place

You have indeed :)

This is the JavaScript Futurize project, related to the Future algebraic type from functional programming. No worries though. It always feels satisfying to close an issue ;)
